/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: cc8a86f62f8e25a32643ed8811d55c03)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	ANTHROPIC_API_KEY: string;
	ASANA_HOUSE_PROJECTS: string;
	ASANA_PROJECT_ID: string;
	ASANA_SECTION_ID: string;
	ASANA_TOKEN: string;
	BLOB_READ_WRITE_TOKEN: string;
	CCB_API_PASSWORD: string;
	CCB_API_URL: string;
	CCB_API_USER: string;
	CLEARSTREAM_API_KEY: string;
	CLEARSTREAM_MCP_USERS: string;
	CLEARSTREAM_RESIDENTS_ACCOUNT_ID: string;
	CONNECT_ADMIN_PASSCODE: string;
	FORMATION_SUPABASE_ANON_KEY: string;
	FORMATION_SUPABASE_URL: string;
	MAINTENANCE_ALERT_NUMBERS: string;
	MAINTENANCE_LINE: string;
	MAINTENANCE_WEBHOOK_SECRET: string;
	PCO_APP_ID: string;
	PCO_SECRET: string;
	PCO_SERVING_WORKFLOW_ID: string;
	PUBLIC_SITE_URL: string;
	STUDIO_PASSCODE: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ANTHROPIC_API_KEY" | "ASANA_HOUSE_PROJECTS" | "ASANA_PROJECT_ID" | "ASANA_SECTION_ID" | "ASANA_TOKEN" | "BLOB_READ_WRITE_TOKEN" | "CCB_API_PASSWORD" | "CCB_API_URL" | "CCB_API_USER" | "CLEARSTREAM_API_KEY" | "CLEARSTREAM_MCP_USERS" | "CLEARSTREAM_RESIDENTS_ACCOUNT_ID" | "CONNECT_ADMIN_PASSCODE" | "FORMATION_SUPABASE_ANON_KEY" | "FORMATION_SUPABASE_URL" | "MAINTENANCE_ALERT_NUMBERS" | "MAINTENANCE_LINE" | "MAINTENANCE_WEBHOOK_SECRET" | "PCO_APP_ID" | "PCO_SECRET" | "PCO_SERVING_WORKFLOW_ID" | "PUBLIC_SITE_URL" | "STUDIO_PASSCODE">> {}
}
